### ISSUE TITLE
Add necessary GCP dependencies to requirements.txt and remove unused GCP deps

### ISSUE THREAD

**Issue by Winterflower** [elastic/anonymize-it#11]
Currently, the code in `anonymize-it`  `writers` module imports the `google` package for interfacing with Google Cloud.
Grepping through the codebase we can find the following two dependencies

```
grep -R --exclude-dir=env google ./*
./anonymize_it/writers.py:from google.oauth2 import service_account
./anonymize_it/writers.py:from google.cloud import storage
```

The `storage` object is used once in the `writers` module

```
grep -R --exclude-dir=env storage ./*
./anonymize_it/writers.py:from google.cloud import storage
./anonymize_it/writers.py:        self.client = storage.Client()
```
whereas `service_account` appears to be unused

```
grep -R --exclude-dir=env service_account ./*
./anonymize_it/writers.py:from google.oauth2 import service_account
```

It seems that we could remove service_account from the imports and add `google.cloud` package to the `requirements.txt`. 
As for the tests, it would probably not be ideal to call into GCP, so we can simply mock out the `storage.Client.get_bucket` method to return some dummy object with same interface as what the code expects. 

```
# example usage of google.cloud.storage in the codebase
grep -R --exclude-dir=env self.client ./*
./anonymize_it/writers.py:        self.client = storage.Client()
./anonymize_it/writers.py:        self.bucket = self.client.get_bucket(self.bucket)
```

Edit: the test methods actually not call into Google Cloud (the only writer that is tested, is the local file system writer), so there is no test-time calls into external systems :)

For reference:
google-cloud-storage package
https://googleapis.github.io/google-cloud-python/latest/storage/client.html

**Comment by blaklaybul** [comment]
I agree, we can mock out a `storage.Client.get_bucket`. Thanks for picking this up.
